# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='importance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
