# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-28 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_document_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
