# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
