# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votedo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doUser', models.IntegerField(null=True)),
                ('agree', models.IntegerField(null=True)),
                ('disagree', models.IntegerField(null=True)),
                ('nothing', models.IntegerField(null=True)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dovote', to='blog.Vote')),
            ],
        ),
    ]
