# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-07 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_votedo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votedo',
            name='vote',
        ),
        migrations.DeleteModel(
            name='Votedo',
        ),
    ]
