# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180507_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_num',
            field=models.IntegerField(null=True),
        ),
    ]
