# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_vote_vote_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='doVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True)),
                ('agree', models.IntegerField(null=True)),
                ('disagree', models.IntegerField(null=True)),
                ('nothing', models.IntegerField(null=True)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doVote', to='blog.Vote')),
            ],
        ),
    ]
