# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_dovote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dovote',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dovote',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dovote',
            name='nothing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dovote',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
