# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 06:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_comment_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_belong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g1', models.CharField(max_length=100, null=True)),
                ('g2', models.CharField(max_length=100, null=True)),
                ('g3', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
