# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180511_1200'),
        ('blog', '0010_auto_20180508_1930'),
    ]

    operations = [
    ]
