# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_user_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_belong',
            name='g2',
        ),
        migrations.RemoveField(
            model_name='user_belong',
            name='g3',
        ),
        migrations.AlterField(
            model_name='user_belong',
            name='g1',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
