# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_merge_20180511_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='disagree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='nothing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post'),
        ),
    ]
