# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180412_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_belong',
            name='g1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='g1s', to='blog.Group'),
        ),
    ]
