# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-11 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_auto_20180511_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='author',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ManyToManyField(default=None, related_name='vote_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
