# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ManyToManyField(default=None, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
