# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180514_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='thisUser',
            field=models.TextField(null=True),
        ),
    ]
