# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_task_thisuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.TextField(),
        ),
    ]
